import {
	AnalyticsApi,
	AuthApi,
	BridgeApi,
	Configuration,
	ImagesApi,
	MailApi,
	MessengerApi,
	PackEmbeddingApi,
	ParserApi,
	PermissionsApi,
	PlaylistEditingApi,
	PlaylistGettingApi,
	SongAddingApi,
	SongDeletingApi,
	SongEditingApi,
	SongFavouritesApi,
	SongGettingApi,
	SongManagementApi,
	SongNotesApi,
	SongPublishingApi,
	SongSearchingApi,
	SongUserManagementApi,
	SongValidationApi,
	TeamAddingApi,
	TeamEditingApi,
	TeamEventsApi,
	TeamGettingApi,
	TeamJoiningApi,
	TeamMembersApi,
	TeamPlaylistsApi,
	TeamSongNotesApi,
	TeamStatisticsApi,
} from '@/api/generated'

export type ApiClasses = ReturnType<typeof getApiClasses>

export const getApiClasses = (apiConfiguration: Configuration) => ({
	playlistGettingApi: new PlaylistGettingApi(apiConfiguration),
	playlistEditingApi: new PlaylistEditingApi(apiConfiguration),
	songGettingApi: new SongGettingApi(apiConfiguration),
	songSearchingApi: new SongSearchingApi(apiConfiguration),
	songAddingApi: new SongAddingApi(apiConfiguration),
	songEditingApi: new SongEditingApi(apiConfiguration),
	songDeletingApi: new SongDeletingApi(apiConfiguration),
	songPublishingApi: new SongPublishingApi(apiConfiguration),
	songValidationApi: new SongValidationApi(apiConfiguration),
	songNotesApi: new SongNotesApi(apiConfiguration),
	songFavouritesApi: new SongFavouritesApi(apiConfiguration),
	authApi: new AuthApi(apiConfiguration),
	permissionApi: new PermissionsApi(apiConfiguration),
	analyticsApi: new AnalyticsApi(apiConfiguration),
	mailApi: new MailApi(apiConfiguration),
	imagesApi: new ImagesApi(apiConfiguration),
	bridgeApi: new BridgeApi(apiConfiguration),
	parserApi: new ParserApi(apiConfiguration),
	packEmbeddingApi: new PackEmbeddingApi(apiConfiguration),
	songManagementApi: new SongManagementApi(apiConfiguration),
	songUserManagementApi: new SongUserManagementApi(apiConfiguration),
	messengerApi: new MessengerApi(apiConfiguration),

	// submodules
	teamAddingApi: new TeamAddingApi(apiConfiguration),
	teamGettingApi: new TeamGettingApi(apiConfiguration),
	teamEditingApi: new TeamEditingApi(apiConfiguration),
	teamJoiningApi: new TeamJoiningApi(apiConfiguration),
	teamMembersApi: new TeamMembersApi(apiConfiguration),
	teamEventsApi: new TeamEventsApi(apiConfiguration),
	teamPlaylistsApi: new TeamPlaylistsApi(apiConfiguration),
	teamSongNotesApi: new TeamSongNotesApi(apiConfiguration),
	teamStatisticsApi: new TeamStatisticsApi(apiConfiguration),
})
