# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to server
on:
  push:
    branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install npm packages
      run: npm install
      
    - name: Build an production version
      run: npm run build
      
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      
    - name: Copy file with SSH
      run: | 
        scp -r build/* root@prijmeni.cz:/var/www/chvalotce
        
    - name: Send message to Messenger
      uses: dkershner6/post-api-call-action@v1
      with:
        url: 'https://chvalotce.cz/sendmessage'
        headers: '{"Content-Type": "application/x-www-form-urlencoded"}'
        data: '{"message": "Nová verze frontendu byla právě nasazena."}'
