name: Tests

on:
  pull_request:
    branches: [master]

jobs:
  wait-for-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for all checks to complete
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          running-workflow-name: 'Tests' # nebo jméno tohoto workflow

  run-tests:
    needs: wait-for-vercel
    runs-on: ubuntu-latest

    steps:
      - name: Get preview deployment URL
        run: |
          echo "PREVIEW_URL=https://preview.chvalotce.cz" >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install deps
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run  test
        env:
          BASE_URL: ${{ env.PREVIEW_URL }}
